
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - export TF_VERSION=1.0.6
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "chmod +x terraform"
      - "ls -al"

  build:
    commands:
      - terraform --version

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'
