
version: 0.2

env:
  exported-variables:
    - BUCKET_ARN

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - export TF_VERSION=1.0.6
      - export TF_LOG=INFO

      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_arm64.zip"
      - "unzip -o terraform.zip"
      - "chmod +x terraform"

      - "cd $CODEBUILD_SRC_DIR"
      

  build:
    commands:
      - "echo $BUILD_HOME/$BUILD_ENV/$BUILD_PIPELINE"
      - "cd $BUILD_HOME/$BUILD_ENV/$BUILD_PIPELINE"
      - terraform init -input=false
      - terraform apply -auto-approve

      - export BUCKET_ARN=terraform output -raw bucket_arn
      - echo "the output bucket arn is $BUCKET_ARN"

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'
